### ISSUE TITLE
SMS/GG button mapping 

### ISSUE THREAD

**Issue by ToddlerPichu** [OtherCrashOverride/go-play#57]
The new SMS/GG emulator switched around the button mapping (was A=1 B=2, now A=2 B=1 ), is there a way to change it back to original mapping?﻿

**Comment by kamotswind** [comment]
I just did a quick Google search for the SMS controller and it looks like the left action button on the SMS (2) would best map to the left action button for Nintendo (B) which is why it may have changed.

**Comment by OtherCrashOverride** [comment]
The change was made because a game (I don't recall which) depended on the physical location of the buttons (left, right).
![sms controller](https://proxy.duckduckgo.com/iu/?u=http%3A%2F%2Fwww.raphnet-tech.com%2Fproducts%2Fgenesis_to_wii%2Fsms_controller.jpg&f=1)

The buttons used can be changed here:
https://github.com/OtherCrashOverride/go-play/blob/04e300aa6ede46c8538761c4a0ac3168305828f9/smsplusgx-go/main/main.c#L658-L659

Since the mapping of B=1 and A=2 match the hardware being emulated, this mapping will continue to be used.
